# all:	kitchen.o main.o
# 	g++ kitchen.o -o laba3

# main.o: main.cpp
# 	g++ -c main.cpp

# kitchen.o: kitchen.cpp povar.h dish.h
# 	g++ -c kitchen.cpp povar.h dish.h

all:
	g++ main.cpp kitchen.cpp povar.h dish.h -o laba3